### ISSUE TITLE
Create2Control in action!

### ISSUE THREAD

**Issue by eliotlandrum** [pomeroyb/Create2Control#11]
This isn't a problem, just wanted to share with you what I'd been working on using Create2Control for. 

https://devpost.com/software/tokenized-autonomous-vehicle-charging-with-blocklet-1ws73v

There's a video at the top. It doesn't show it, but the Roomba has a Pi inside the vacuum area and there's a Pi for the dock as well (not shown). I use the Create2 library to transition the bot from cleaning & docking modes. Due to some other-library compatibilities, I used a quickly converted Python 3 version of the main script within my own package... it's not very clean, so didn't want to do a PR at this time for it. Thanks for sharing your work on this library! It was very useful to us.

**Comment by pomeroyb** [comment]
Thanks for sharing your project!
