### ISSUE TITLE
No setup.py and config weirdness

### ISSUE THREAD

**Issue by MustacheEmperor** [pomeroyb/Create2Control#3]
Because there's no setup.py I have to append the directory to pythonpath manually and use it locally. I think because of this, the program can't find config.json unless I hardcode in the entire path for config's fname. 

Sorry if this is a useless issue report - I'm new at this! Thanks for writing this library. I'll try to contribute.

**Comment by pomeroyb** [comment]
The way I currently have it running is to just have "create2api.py" and "config.json" in the same folder as the python script that is using it.

Definitely not a useless issue -- It's something that I thought about implementing, but it just didn't take priority over api features. Now that I know that there is at least one other person using the api, I'll try to take a look at it. :)

**Comment by MustacheEmperor** [comment]
Great! If I can figure it out before you I may add it to my fork. I'm working on implementing sound now and have it partly working, I'll submit a pull request when it's all functional. Thanks for all your work on this so far by the way, saved me an insane amount of time getting started with this
