### ISSUE TITLE
Need to know how to access create2api from web server!

### ISSUE THREAD

**Issue by papablank** [pomeroyb/Create2Control#7]
First of all I want to thank you so much for writing this create2api code in python. I'm a student at Northcentral Technical College in Wisconsin and I'm using the Create2 for my final project in the Electromechanical Technology program. I came across your code and was able to install it (took me a while but it was worth it!) and am now controlling my Create2 using python which is awesome. 

**Here is my issue:** I am very new to programming in Python, and have a little experience making websites. I need to run your create2api code on my RaspberryPi 3 to make my robot move via a web interface. There is almost no documentation or videos out there on doing this - or else I am too much of a noob to find it.

Can you point me in the right direction toward a web development tool that will allow me to interface with your create2api code on the Rpi ?

**Comment by pomeroyb** [comment]
Hey there, glad to hear the code is working for you!

I am not super familiar with networking either, unfortunately. The method I would probably use is something like connecting a json stream from your webpage to your Pi using sockets. A python script on the Pi would read the incoming json and watch for certain commands, then make the correct function calls using the api.

But I'm really not a good person to ask -- I've never really dabbled in this area. Let me know if you make some progress!

**Comment by papablank** [comment]
Thank you for your ideas! I will let you know how it turns out.
